### PR TITLE
Fix `animated` parameter not taking effect #97

### LINKED ISSUE #97: `animated: false` is not taking effect in Settings 3.0
In creating a `SettingsWindowController`, even `animated: false` is passed to initializer, the settings window still animates.

### PR DESCRIPTION
**Pull request by francisfeng**
`isSubset(of:)` will always return true even when `NSViewController.TransitionOptions` is empty.

Fixes #97

### CODE REVIEW

File: Sources/Settings/SettingsTabViewController.swift [hunk 1]
```diff
@@ -153,17 +153,21 @@ final class SettingsTabViewController: NSViewController, SettingsStyleController
...
+      return options.isSubset(of: [
+        .crossfade,
+        .slideUp,
+        .slideDown,
+        .slideForward,
+        .slideBackward,
+        .slideLeft,
+        .slideRight
+      ])
+    }()
```
Comment (sindresorhus) [inline Sources/Settings/SettingsTabViewController.swift:170]: It can just be:

```swift
let isAnimated = !options.isEmpty && options.isSubset(of: [
    .crossfade,
    .slideUp,
    .slideDown,
    .slideForward,
    .slideBackward,
    .slideLeft,
    .slideRight
])
```

Also use tab-indetation.
